[config]
	# Default: 10
	# Range: > 1
	historical_scroll_speed = 10
	sound_interruption_enabled = true
	# Default: 20
	# Range: > 1
	char_per_second = 20
	# Default: 100
	# Range: 1 ~ 200
	portrait_width_percent = 100
	#Disable mouse scroll action in the chatbox screen (scroll up for log, down as mouse click)
	#禁用对话框屏幕的：向上滚动到历史记录，向下滚动同鼠标点击
	disable_mouse_scroll = false
