#The default difficulty selected for newly created worlds.
#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
defaultDifficulty = "HARD"
#Set to true if the difficulty for new world's should be locked to the specific default. This cannot be unlocked by players without external tools! Probably a bad idea. I don't recommend. Why am I adding this option?
lockDifficulty = false
#Resource pack IDs to have enabled by default on the first run.
defaultResourcePacks = ["serilum_mod_translations", "vanilla", "mod_resources", "moonlight:merged_pack", "mod/continuity:resourcepacks/default", "mod/continuity:resourcepacks/glass_pane_culling_fix", "mod/eternal_starlight:resourcepacks/starlight_3d_mace", "mod/yuushya:resourcepacks/mcpatcher_feature", "file/Icon Xaero's 1.22.zip", "file/BeLoong Gui V3.zip", "file/Assorted Allays x FA - V.11.0.zip", "[无缝玻璃] Clear Glass Pack 1.21.zip", "[更好的草和蕨] Os' Colorful Grasses (Mix).zip", "[更好的草方块] Fast Better Grass.zip"]
