##决定 晶咒飞弹落地后 产生的晶咒之径 每条路径的最大前进距离
# 根据: 技能等级

##Determining the Maximum Forward Distance of Each Path Generated by the Crystal Path After Crystcursed Missile Lands
# Based on: Skill Level

function crystcursed_dragon:lib/level_based_value/main { \
    function: { \
        type: "clamped", \
        max: 10f, \
        min: 0f, \
        value: { \
            type: "linear", \
            base: 6f, \
            per_level_above_first: 2f \
        } \
    } \
}